import './globals.css';
import Nav from './components/Nav';
import { getServerSession } from 'next-auth/next';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import Hydrate from './components/Hydrate';

export const metadata = {
  title: 'E-commerce Platform',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // fetch user
  const session = await getServerSession(authOptions);
  // {
  //   user: {
  //     name: 'Violet Kester',
  //     email: 'kester.violet.j@gmail.com',
  //     image: 'https://lh3.googleusercontent.com/a/AAcHTtdEdiHl8XFIZQsbmd57kyTXwYSSt88ItQRyE5oCYeNCzA=s96-c'
  //   }
  // }
  return (
    <html lang='en'>
      <body className="mx-64">
        <Hydrate>
          <Nav user={session?.user} expires={session?.expires as string} />
          {children}
        </Hydrate>
      </body>
    </html>
  );
}